name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Add MSVC to PATH
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@release/v1

      - name: Build
        shell: bash
        run: |
          mkdir -p build
          case "$RUNNER_OS" in
            "Windows")
              # MSVC compiler (cl.exe) on Windows
              cl -EHsc -W4 -Fe:build\\main.exe CIS25-Project-1\\*.cpp
              ;;
            "macOS")
              # Clang compiler on macOS
              clang++ -std=c++11 -o build/main CIS25-Project-1/*.cpp
              ;;
            "Linux")
              # GCC compiler on Ubuntu
              g++ -std=c++11 -o build/main CIS25-Project-1/*.cpp
              ;;
          esac
  
      - name: Test
        shell: bash
        run: |
          echo usd > stdin.txt
          echo lb >> stdin.txt
          echo 1 >> stdin.txt
          case "$RUNNER_OS" in
            "Windows")
              ./build/main.exe < stdin.txt
              ;;
            *)
              ./build/main < stdin.txt
              ;;
          esac